version: '3'

services:
  ## FRONTEND MAIN
  frontend-main:
    image: docker.pkg.github.com/communitydragon/dragoncore/frontend-main:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/prod/vue/Dockerfile
      args:
        project_dir: frontend/main 

  ## FRONTEND DEVELOPER
  frontend-developer:
    image: docker.pkg.github.com/communitydragon/dragoncore/frontend-developer:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/prod/vue/Dockerfile
      args:
        project_dir: frontend/developer 

  ## FRONTEND AUTH
  frontend-developer:
    image: docker.pkg.github.com/communitydragon/dragoncore/frontend-auth:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/prod/vue/Dockerfile
      args:
        project_dir: frontend/auth 