version: '3'

services:
  ## FRONTEND MAIN
  frontend-main:
    image: docker.pkg.github.com/communitydragon/dragoncore/frontend-main:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/prod/vue/Dockerfile
      args:
        project_dir: frontend/main 