name: publish

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build unversioned images
        run: VERSION="commit-$(git rev-parse --short ${{ github.sha }})" docker-compose -f docker-compose.build.yml build

      - name: Build versioned images
        run: |
          IMAGE_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          if [ "$IMAGE_TAG" == "master" ]
          then
            VERSION=latest docker-compose -f docker-compose.build.yml build
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]
          then
            VERSION=$(echo $IMAGE_TAG | sed -e 's/^v//') docker-compose -f docker-compose.build.yml build
          fi

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push unversioned image to registry
        run: VERSION="commit-$(git rev-parse --short ${{ github.sha }})" docker-compose -f docker-compose.build.yml push

      - name: Push versioned image to registry
        run: |
          IMAGE_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          if [ "$IMAGE_TAG" == "master" ]
          then
            VERSION=latest docker-compose -f docker-compose.build.yml push
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]
          then
            VERSION=$(echo $IMAGE_TAG | sed -e 's/^v//') docker-compose -f docker-compose.build.yml push
          fi